openapi: 3.0.0
info:
  title: nko-linka-wordpress
  version: 1.0.0
paths:
  /internal:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 404
        http_headers:
          Content-Type: application/json
        content:
          application/json: '{"error":"not found"}'
  /internal/run-recurring-donations:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 404
        http_headers:
          Content-Type: application/json
        content:
          application/json: '{"error":"not found"}'
  /internal/{proxy+}:
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 404
        http_headers:
          Content-Type: application/json
        content:
          application/json: '{"error":"not found"}'
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba644mi7027h56etnsd
        service_account_id: aje9j1qvtr8csrsr28d7
  /{proxy+}:
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bba644mi7027h56etnsd
        service_account_id: aje9j1qvtr8csrsr28d7
