ServerName nkolinka.ru
UseCanonicalName Off
UseCanonicalPhysicalPort Off
RedirectMatch 301 ^/wp-admin$ https://nkolinka.ru/wp-admin/

<Directory /var/www/html>
    Options FollowSymLinks
    AllowOverride All
    Require all granted

    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.php [L]
</Directory>
